---
id: 65ef198fde24dfb7ff675b42
title: Passo 4
challengeType: 20
dashedName: step-4
---

# --description--

A instrução `raise` permite que você force a ocorrência de uma exceção específica.Ele consiste na palavra-chave `raise` seguida pelo tipo de exceção e permite que você forneça uma mensagem de erro personalizada:

```py
raise ValueError("Invalid value")
```

Quando o código acima é executado, um `ValueError` é gerado e a mensagem `"Invalid value"` é exibida para o usuário.

Se o `square_target` for menor que `0`, nenhuma raiz quadrada de valor real pode ser calculada.Portanto, levante um `ValueError` com a mensagem `'Square root of negative number is not defined in real numbers'`.Não esqueça de remover a palavra-chave `pass`.

# --hints--

Você deve remover a palavra-chave `pass`.

```js
({
    test: () => {
        assert.isFalse(runPython(`_Node(_code).find_function("square_root_bisection").find_ifs()[0].find_bodies()[0].has_pass()`))
    }
})
```

Você deve levantar um `ValueError` com a mensagem `'Square root of negative number is not defined in real numbers'` dentro do corpo do `if`.

```js
({
    test: () => {
        
        assert(runPython(`_Node(_code).find_function("square_root_bisection").find_ifs()[0].find_bodies()[0].is_equivalent("raise ValueError('Square root of negative number is not defined in real numbers')")`))
    }
})
```

# --seed--

## --seed-contents--

```py
--fcc-editable-region--
def square_root_bisection(square_target, tolerance=1e-7, max_iterations=100):
    if square_target < 0:
        pass

--fcc-editable-region--
```
